# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        gc_maxlifetime: 7200
        cookie_lifetime: 7200

    #esi: true
    #fragments: true

    assets:
        packages:
            easyadmin:
                json_manifest_path: '%kernel.project_dir%/public/bundles/easyadmin/manifest.json'
                base_path: '/bundles/easyadmin'

    http_client:
        default_options:
            timeout: 180
            max_duration: 180

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
