framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        message_bus: false
        envelope:
            sender: 'admin-portfolio@f5t.com'
        headers:
            From: 'Portfolio <admin-portfolio@f5t.com>'